[package]
name = "oxid_spec"
version = "0.1.0"
edition = "2021"

[dependencies]
oxide-core = { path = "../../oxide-core" }
oxidz80 = { path = "../../oxidz80" }
oxid_display = { path = "../../oxid_display" }
oxid_input = { path = "../../oxid_input" }
minifb = "0.24.0"
