[package]
name = "oxidz80"
version = "0.1.0"
edition = "2024"

[dependencies]
oxide-core = { path = "../oxide-core" }

[dev-dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"
